# Generated by Django 3.0.5 on 2021-05-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0002_auto_20210520_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='powerThreshold',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='servers',
            name='tempThreshold',
            field=models.IntegerField(null=True),
        ),
    ]
