# Generated by Django 3.0.5 on 2021-05-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0004_servers_grafanauid'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='grafanaId',
            field=models.IntegerField(null=True),
        ),
    ]
