# Generated by Django 3.0.5 on 2021-04-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=70)),
                ('ip', models.CharField(blank=True, default='', max_length=200)),
                ('os', models.CharField(blank=True, default='', max_length=50)),
                ('iType', models.CharField(blank=True, default='', max_length=50)),
                ('keyPair', models.CharField(blank=True, default='', max_length=100)),
                ('area', models.CharField(default='', max_length=50)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
