version: "3"

services:
  db:   # 서비스이름
    image: mysql:8.0.17  # 이미지
    container_name: mysql   # 컨테이너 이름
    ports:
      - "3306:3306"   # 포트 설정  외부:내부
    environment:
      MYSQL_ROOT_PASSWORD: "redfish21"   # 패스워드설정
    command:
      - --character-set-server=utf8mb4      # 인코딩
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - .db/mysql:/var/lib/mysql    # 마운트 설정

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"
    
  nginx:
    image: nginx:latest # nginx 서비스에서 사용할 도커 이미지
    ports:
      - "80:80"
    volumes:
      - ./app:/app
      - ./config/nginx:/etc/nginx/conf.d
    depends_on: # 서비스 간의 종속성 표현
      - app
